// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeSmzZGRKWj8bvcrnhzG1DU5NQTeVxD6M',
    appId: '1:447567628887:web:d8a2c15711bf9ca29b3112',
    messagingSenderId: '447567628887',
    projectId: 'travel01-401212',
    authDomain: 'travel01-401212.firebaseapp.com',
    databaseURL: 'https://travel01-401212-default-rtdb.firebaseio.com',
    storageBucket: 'travel01-401212.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8a1ZxU50P6HzVB2CzjbDEiGuxKdd7qvM',
    appId: '1:447567628887:android:1d2c5938bf11103d9b3112',
    messagingSenderId: '447567628887',
    projectId: 'travel01-401212',
    databaseURL: 'https://travel01-401212-default-rtdb.firebaseio.com',
    storageBucket: 'travel01-401212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7NhsUrDRycfzHylD9SFZYTnves-gdLmY',
    appId: '1:447567628887:ios:74ab1cdad9bb7e919b3112',
    messagingSenderId: '447567628887',
    projectId: 'travel01-401212',
    databaseURL: 'https://travel01-401212-default-rtdb.firebaseio.com',
    storageBucket: 'travel01-401212.firebasestorage.app',
    iosBundleId: 'com.example.oooh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7NhsUrDRycfzHylD9SFZYTnves-gdLmY',
    appId: '1:447567628887:ios:74ab1cdad9bb7e919b3112',
    messagingSenderId: '447567628887',
    projectId: 'travel01-401212',
    databaseURL: 'https://travel01-401212-default-rtdb.firebaseio.com',
    storageBucket: 'travel01-401212.firebasestorage.app',
    iosBundleId: 'com.example.oooh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeSmzZGRKWj8bvcrnhzG1DU5NQTeVxD6M',
    appId: '1:447567628887:web:da57144a6e309c2d9b3112',
    messagingSenderId: '447567628887',
    projectId: 'travel01-401212',
    authDomain: 'travel01-401212.firebaseapp.com',
    databaseURL: 'https://travel01-401212-default-rtdb.firebaseio.com',
    storageBucket: 'travel01-401212.firebasestorage.app',
  );
}
